### ISSUE TITLE
"+" character

### ISSUE THREAD

**Issue by nitrotore** [sepich/SynNotes#1]
if I write a note with the "+" character, for example "hello + hello", in Simplenote is synchronized as "hello hello".
When I run the synchronization again in SynNotes becomes "hello hello".
"+" char is turned in " " (space) char

**Comment by sepich** [comment]
Thanks for finding out such a major issue!
Should be fixed in 150430

**Comment by nitrotore** [comment]
Thanks for fix! You did a great job!

Il 30/04/2015 21:41, sepich ha scritto:
