### ISSUE TITLE
SQL keywords highlight

### ISSUE THREAD

**Issue by fureya** [sepich/SynNotes#2]
Hey mate, first of all i'd like to congratulate you. Your app is GREAT! Much better than many paid apps outthere. 

Only problem that i encounter is highlighting SQL syntax. As you can see on the link below even most simple statements like SELECT or FROM are not highlighted.

http://scr.hu/1ia/8fz90

**Comment by sepich** [comment]
Thanks.
Issue with SQL syntax is that keywords are not built in scintilla lexer,
but provided in theme file (where colors are defined). Could be checked in
notepad++ theme settings.
I'll take a look on how to read keywords too and add them to lexer at
runtime.

**Comment by sepich** [comment]
Should be fixed by ff9b1230d5994656387c3e1edc58ef2ed658b202
Please try new binary.
