### ISSUE TITLE
unable to start after setting custom hotkeys

### ISSUE THREAD

**Issue by maiklos** [sepich/SynNotes#3]
when I edit settings.ini file to this:

<pre>
[Form]
WindowState=Minimized
[Scintilla]
Theme=Visual Studio.xml
[Keys]
HotkeyShow=Alt+1
HotkeySearch=Alt+2
</pre>

then SynNotes is not able to start. After 2-3 seconds following is displayed:

![synnotes_2015-09-18_10-02-08](https://cloud.githubusercontent.com/assets/251009/9954850/8e8aa092-5dec-11e5-8515-4e780cccc8a5.png)

**Comment by sepich** [comment]
Tried with the same ini content and was unable to reproduce on 8.1x64 and 7x32.
Which version do you use?
Could you try leaving only Keys section in ini?

**Comment by maiklos** [comment]
version: 150430  - I will retest with later version

**Comment by maiklos** [comment]
yeap, it works with 150824.
thanks
